/**
 *  navigation.safeargs 该插件内部使用了 kotlinpoet 生成代码库，
 *  根项目引入的插件会覆盖子模块的插件，导致冲突。
 *  所以在子模块引入该插件, 避免与我们的 build-logic -> plugins 插件中的 kotlinpoet 产生冲突
 */
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'io.realm.kotlin'
    id "org.jetbrains.kotlin.kapt"
    id 'androidx.navigation.safeargs'
//    id 'dev.shuanghua.plugin.asmbytecode'
}


def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))


android {
    lint {
        baseline = file("lint-baseline.xml")
    }

    namespace 'com.shua.likegank'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    compileSdk 34

    defaultConfig {
        applicationId "com.shua.likegank"
        minSdk 23
        targetSdk 34

        versionCode 16
        versionName "6.0.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            //遍历输出文件
            android.applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    def outputFile = output.outputFile
                    if (outputFile != null && outputFile.name.endsWith('release.apk')) {
                        def fileName =
                                "release_likegank_${defaultConfig.versionName}" +
                                        "_${defaultConfig.versionCode}" +
                                        "_${variant.buildType.name}" + ".apk"
                        outputFileName = fileName
                    }
                }
            }
        }
    }

    buildFeatures {
        viewBinding true
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation libs.material

    implementation libs.swiperefreshlayout
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx

    implementation libs.retrofit
    implementation libs.converter.gson

    implementation libs.rxandroid
    implementation libs.rxjava

    implementation libs.rxpermissions
    implementation libs.multitype
    implementation libs.glide
    implementation libs.timber
    implementation libs.library

//    implementation 'dev.shuanghua.library:nav-annotation:1.0.0' // 仓库依赖
    implementation project(':nav-annotation') // 直接代码依赖
    kapt project(':nav-compiler')
    implementation libs.retrofit2.adapter.rxjava3

    implementation libs.realm.kotlin.base
    implementation libs.kotlin.coroutines.rx3
}