plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation gradleApi()

    implementation localGroovy()

    implementation "commons-io:commons-io:2.16.1"
    implementation "org.ow2.asm:asm:9.7"
    implementation "org.ow2.asm:asm-tree:9.7"

    implementation "com.squareup:kotlinpoet:1.16.0"
}